config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :user 
  root to: "tweets#index"
  resources :tweets,except:[:show]	
  resources :users, only:[:show]
end

app/models/add_user_id.rb
class AddUserId < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :tweets, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :move_to_index, except: [:index]

  def index
    @tweets = Tweet.includes(:user).order(created_at: :DESC).page(params[:page]).per(3)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    Tweet.create(tweets: tweet_params[:tweets],user_id: current_user.id)
    redirect_to action: "index"
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end


  def update
    tweet = Tweet.find(params[:id])
    
    tweet.update(tweets: tweet_params[:tweets],user_id: current_user.id)
     else
    redirect_to :action => "index"
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to :action => "index"
  end

  private
  def tweet_params
    params.require(:tweet).permit(:tweets)
  end

  def move_to_index
    redirect_to action: "index" unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @tweets = current_user.tweets.page(params[:page]).per(2).order("created_at DESC")
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniTweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
   <header>
     <div class="header-logo">
        <%= link_to "miniblog",  root_path %>
      </div>

        <div class="headder-menu">
      <% if user_signed_in? %>
      
        <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'headder-menu' %></p>
        <p><%= link_to "新規投稿", new_tweet_path, class: 'headder-menu' %></p>
       <p><%= link_to "マイページ","/users/#{current_user.id}", class: 'headder-menu' %></p>
       
        <% else %>
            <%= link_to "ログイン", new_user_session_path, class: 'headder-menu' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'headder-menu'%>
            </div>
      <% end %>
        
  </header>
    <%= yield %>
  </body>
</html>

app/views/tweets/_tweet.html.erb
 <span>投稿者名:<%= tweet.user.name%></span>
      <div class="box-text">
        <p class="box_text"><%= tweet.tweets%></p>
      </div>
    <% if user_signed_in? && current_user.id == tweet.user_id %>
        <ul>
         <%= link_to "削除", tweet_path(tweet), method: :delete, data: {confirm: "削除しますか?"} %></li>
         <%= link_to "編集", edit_tweet_path(tweet)%></li>
        </ul>
    <%end%>

app/views/tweets/edit.html.erb
<%= form_for @tweet, url: tweet_path, html: { method: :patch } do |f| %>
   <h1>テキスト編集</h1>
  <p><%= f.text_area :tweets, style: 'width: 900px;height: 300px;' %></p>
  <input type="submit" value="送信" > 
<% end %>

app/views/tweets/index.html.erb
<div class="container">
<div class="box">
  <%= render  @tweets %>
</div>
<%= paginate(@tweets)%>
 </div>

<%# <%= render  partial: "tweet",locals: { tweet: tweet } %>

app/views/tweets/new.html.erb
<div class="form-group">
<%= form_for @tweet, url: tweets_path, method: :post do |f| %>
  <h2>新規登録</h2>
  <p><%= f.text_area :tweets,placeholder: 'ブログを投稿して下さい', style: 'width: 900px;height: 300px;' %></p>
  <input type="submit" value="送信" class="btn btn-outline-success">
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="box">
  <%= render  @tweets %>
</div>
<%= paginate(@tweets) %>
 </div>